---
functional:
  - Пользователь может зарегистрироваться на сайте стандартным способом и через GitHub 
  - Вход в систему осуществляется по логину и паролю
  - На главной странице отображается история игр и турниров
  - У пользователя должна автоматически создаваться личная страница в которой отображен никнейм, рейтинг, количество сыгранных игр, количество побед, поражений, сдавшихся игр, основной язык программирования и дата регистрации
  - При наведении курсора на никнейм всплывает окошко с информацией о количестве побед, поражений, сдавшихся, никнейм, основной язык программирования, кнопка подписаться и кнопка с предложением поединка
  - Есть возможность создать новую игру (выбрать язык, уровень сложности, тематику кода, время и тип соперника человек/бот)
  - В игру можно играть с любым человеком, с ботом или другом
  - При создании игры можно выбрать определенную игру, иначе она будет подобрана наугад
  - Любого игрока можно вызвать на поединок
  - Сайт предоставляет задачи по программированию
  - В процессе игры есть возможность писать и запускать код
  - По завершению игры осуществляется проверка правильности решения
  - Есть ограничение по времени
  - На главной странице есть общий чат
  - На главной странице отображаются лидеры недели, месяца и за весь период
  - Есть возможность просмотра завершённых сражений
  - Есть возможность добавлять новые языки программирования
  - Есть возможность поставить звезду проекту на GitHub
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
  - Быстрое отображение списка игр и участников
  - Мгновенный запуск поединка
  - Обработка сбоев соединения, авто-переподключение к игре
  - Адекватный интерфейс на экранах от 768 px и выше
  - Защита от читов
implicit:
  - Интуитивный интерфейс, кнопка «Драться» заметна, чат доступен
  - Наличие званий, рейтинга, очков, турниров, аватарок, звёзд, эмодзи
  - Видно, кто сейчас в лобби
  - Есть напоминание о том, что необходимо быть вежливыми в чате
  - Блокировка токсичного контента
  - Отображается состояние игроков (ожидает/играет)
  - Есть уровни, которые растут
  - Визуальные элементы говорят больше, чем длинный текст
