---
functional:
  - Пользователь может зарегистрироваться на сайте стандартным способом, через GitHub и Discord
  - Вход в систему осуществляется по логину и паролю
  - На главной странице отображается история игр и турниров
  - Авторизованный пользователь может создать игру одним нажатием кнопки Create game
  - Выбор языка и других параметров возможен при создании игры
  - После создания игры с другим игроком пользователь попадает в режим ожидания второго игрока
  - У пользователя должна автоматически создаваться личная страница в которой отображен никнейм, рейтинг, количество сыгранных игр, количество побед, поражений, сдавшихся игр, основной язык программирования и дата регистрации
  - При наведении курсора на никнейм всплывает окошко с информацией о количестве побед, поражений, сдавшихся, никнейм, основной язык программирования, кнопка подписаться и кнопка с предложением поединка
  - Есть возможность создать новую игру (выбрать язык, уровень сложности, тематику кода, время и тип соперника человек/бот)
  - В игру можно играть с любым человеком, с ботом или другом
  - Игра, созданная первым игроком, отображается как доступная для подключения у пришлашенного пользователя
  - Второй пользователь может подключиться к доступной игре, нажав кнопку Connect to game
  - После подключения второго игрока оба участника попадают в игровой интерфейс
  - При создании игры можно выбрать определенную игру, иначе она будет подобрана наугад
  - Любого игрока можно вызвать на поединок
  - Каждый игрок видит изменения кода соперника в реальном времени
  - У каждого игрока есть кнопка Check для проверки решения
  - Количество попыток проверки решения не ограничено
  - Если один из игроков вылетает, второй продолжает игру; первый может переподключиться в любой момент до окончания игры
  - Сайт предоставляет задачи по программированию
  - В процессе игры есть возможность писать и запускать код
  - По завершению игры осуществляется проверка правильности решения
  - Время игры пока не ограничено
  - Игра завершается, когда один из игроков находит правильное решение
  - После завершения выводится модальное окно с указанием победителя
  - Победитель получает кнопку Exit
  - Кнопка Check становится неактивной после завершения поединка, но игрок может остаться и просмотреть свой код
  - Проигравший также может выйти из игры или продолжить решение
  - Когда оба игрока покинули игру, она считается завершённой и удаляется из памяти
  - На главной странице есть общий чат
  - На главной странице отображаются лидеры недели, месяца и за весь период
  - Есть возможность просмотра завершённых сражений
  - Есть возможность добавлять новые языки программирования
  - Есть возможность поставить звезду проекту на GitHub
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Игровой интерфейс сайта содержит редактор кода слева — собственный код игрока
  - Игровой интерфейс сайта содержит правый редактор кода — код соперника в режиме реального времени
  - Игровой интерфейс сайта содержит таймер игры в верхней части экрана
  - Игровой интерфейс сайта содержит задание, расположенное под таймером 
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
  - Быстрое отображение списка игр и участников
  - Мгновенный запуск поединка
  - Обработка сбоев соединения, авто-переподключение к игре
  - Адекватный интерфейс на экранах от 768 px и выше
  - Защита от читов
implicit:
  - Интуитивный интерфейс, кнопка «Драться» заметна, чат доступен
  - Наличие званий, рейтинга, очков, турниров, аватарок, звёзд, эмодзи
  - Видно, кто сейчас в лобби
  - Есть напоминание о том, что необходимо быть вежливыми в чате
  - Блокировка токсичного контента
  - Отображается состояние игроков (ожидает/играет)
  - Есть уровни, которые растут
  - Визуальные элементы говорят больше, чем длинный текст
